services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/src/backend
    environment:
      PYTHONPATH: /app/src:/app/src/backend
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      ENDPOINT_URL: ${ENDPOINT_URL}
      MONGO_ROOT_USER: admin
      MONGO_ROOT_PASSWORD: password123
      MONGO_DB_NAME: karaokeexpert
      MONGO_PORT: 27017
      
    networks:
      - app-network
    command: flask --app backend.app.app run --host=0.0.0.0 --port=5000
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    # env_file: ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: karaokeexpert
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  minio-setup:
    image: minio/mc
    container_name: minio_setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: songs
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing local/$${MINIO_BUCKET_NAME};
      exit 0;
      "
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: