services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: flask --app app.app run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    # env_file: ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network
      
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"


networks:
  app-network:
    driver: bridge