# pytest.ini
[pytest]
env =
    MINIO_ROOT_USER=mock-minio-admin
    MINIO_ROOT_PASSWORD=mock-minio-password123
    ENDPOINT_URL=http://localhost:9000
    MONGO_ROOT_USER=mock-mongo-admin
    MONGO_ROOT_PASSWORD=mock-mongo-password123
    MONGO_DB_NAME=karaokeexpert_test
    MONGO_PORT=27017
    MINIO_BUCKET_NAME=songs
    REDIS_HOST=localhost
    REDIS_PORT=6379
    KAFKA_PORT=9209